### ISSUE TITLE
can i bake multiple matirial into one lightmap with this tool and how can i do it ?

### ISSUE THREAD

**Issue by bibidentuhanoi** [Naxela/The_Lightmapper#176]
first of all your tool is amazing, it gives me the best result out of all the other addons I have tried. but I cant seem to find a way to bake everything into one big lightmap. is there a way I can achieve this with your addon? THanks

**Comment by Naxela** [comment]
Hi, and thanks for using the addon!

If I understood you correctly, you want to bake the whole scene down to one lightmap rather than multiple lightmaps?

It's possible using the **atlas function** located near the bottom of the lightmapper panel (I think it's called additional). There you can add as many objects to the same lightmap as you want, possibly the whole scene. - The downside is that I haven't documented this anywhere. - I can probably make a quick video that describes the process sometime in the weekend

**Comment by bibidentuhanoi** [comment]
so after running a few tests, I notice a problem the tool only bakes 1 object only even tho there are 2 in the collection and if I put more than 2 objects in there, the whole lightmap will be black

![image](https://github.com/Naxela/The_Lightmapper/assets/95683666/3340be40-53d2-4586-b273-6ac281783ed1)
![image](https://github.com/Naxela/The_Lightmapper/assets/95683666/f3d5a2a2-775e-43f2-94d0-832002d69f5b)

**Comment by Naxela** [comment]
Oh, I forgot to mention that was a bug I fixed recently. Are you using the addon from the releases page? I recommend getting it straight from the green download button at the top (code => download zip): https://github.com/Naxela/The_Lightmapper/archive/refs/heads/master.zip

Let me know if it works

**Comment by bibidentuhanoi** [comment]
i have just tested it out and sadly the problem is still there 
![image](https://github.com/Naxela/The_Lightmapper/assets/95683666/fce3387a-21b1-4e8b-8db4-99434cc800d4)

**Comment by Naxela** [comment]
Hi, I can confirm that I seem to be getting the same error in the latest version of Blende 3.5 (Maybe just 3.51) - Which version do you use? - I couldn't seem to be able to reproduce it in Blender 3.3.

In any case, I pushed a fix that should be able to fix it:
https://github.com/Naxela/The_Lightmapper/commit/a37f478e8ad79378d3bafa2fc76cc5c8bea38ebb

Could you check if it works now?

**Comment by bibidentuhanoi** [comment]
Hi, so I just checked, and everything worked perfectly. At first, I tried this fix with Blender version 3.4, but it did not work. After upgrading Blender to your version, everything works. I have also tested the previous version of your code with Blender 3.5, and the result was still the same as before (only a black lightmap). 


Thank you for developing this program; it has saved me a significant amount of time while producing a light map. And, as you previously said, you intend to make a video for this feature. If you haven't already done so, I would be happy to help you. I'd also like to test this tool further, and perhaps I could help you in creating documentation for this add-on.

**Comment by Naxela** [comment]
Thanks for testing it out, seems like there's still a bit of work to make it work for other Blender versions.

As for documentation, any help with this would be much appreciated! - especially since I don't have much time myself and there's a surprisingly big amount of users
